#!/bin/bash
#small script to mount a share through sshfs or samba depending if you're in or out of the local network
kindofconnection="${1:-internal}"
internalip="" 
externalip="" 
port="" #ssh port to use 
path="" #path the share must be mounted on
rasppath="" #path of the share
share="" #the samba share
username="" #the username to use 

if [ $kindofconnection == 'internal' ]; then
	sudo mount.cifs //$internalip$share $path -o username=$username,iocharset=utf8
elif [ $kindofconnection == 'external' ]; then
	sshfs -p $port $username@$externalip:$rasppath $path
else
	echo "Your argument didn't make any sense to me, usage: raspmount external/internal"
fi

