#!/bin/bash
#small script to switch monitors, needs changing to work for someone else
monitor="${1:-laptop}"
fullcolor="${2:-n}"

if [ $monitor == 'laptop' ]; then
	xrandr --output HDMI2 --off
	xrandr --output eDP1 --auto
else
	xrandr --output eDP1 --off
	xrandr --output HDMI2 --auto
	if [ $fullcolor == 'y' ]; then
		xrandr --output HDMI2 --set "Broadcast RGB" "Full"
	fi
fi
