#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case $BLOCK_BUTTON in
  1) pavucontrol ;; #left click, start mixer
  3) ponymix toggle > /dev/null ;; # right click, mute/unmute
  4) ponymix increase 10 > /dev/null ;;    # scroll up, increase
  5) ponymix decrease 10 > /dev/null ;;    # scroll down, decrease
esac

VOLUME=" $(ponymix get-volume)%"
MUTED=$(ponymix list | grep -A 2 "sink 1" | grep "Muted")
echo "$VOLUME"
echo

if [ "${MUTED}" ]; then
	echo \#F7726E
fi

