#!/bin/bash

kindofconnection="${1:-internal}"
internalip="intip"
externalip="extip"
port="port"
path="path"
rasppath="rasppath"
share="share"
username="username"

if [ $kindofconnection == 'internal' ]; then
	sudo mount.cifs //$internalip$share $path -o username=$username,iocharset=utf8,uid=1000
elif [ $kindofconnection == 'external' ]; then
	sshfs -p $port $username@$externalip:$rasppath $path
else
	echo "Your argument didn't make any sense to me, usage: raspmount external/internal"
fi

