#!/bin/bash

monitor="${1:-laptop}"
fullcolor="${2:-n}"

if [ $monitor == 'laptop' ]; then
	xrandr --output VGA-0 --off
	xrandr --output LVDS --auto
else
	xrandr --output LVDS --off
	xrandr --output VGA-0 --auto
	if [ $fullcolor == 'y' ]; then
		xrandr --output HDMI2 --set "Broadcast RGB" "Full"
	fi
fi
