#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CARD="${1:-0}"
MIXER="${2:-pulse}" # use pulse for pulseaudio, default is alsa
VOLUME="$(pulseaudio-ctl full-status | awk '{ print $1;}')"

case $BLOCK_BUTTON in
  1) pavucontrol ;; #left click, start mixer
  3) pulseaudio-ctl mute ;; # right click, mute/unmute
  4) pulseaudio-ctl up;;    # scroll up, increase
  5) pulseaudio-ctl down ;;    # scroll down, decrease
esac

echo " $VOLUME%"
echo

MUTED="$(pulseaudio-ctl full-status | awk '{ print $2;}')"
if [ "$MUTED" == "yes" ]; then
	echo \#ed6b6b
fi

